### ISSUE TITLE
Avatar is not diplayed for new users

### ISSUE THREAD

**Issue by yurilaaziz** [eyacom/ctf-platform-bugs#1]
**Describe the bug**

- [ ] Login / Register / Authentication / Authorization
- [x] User's profile display / User profile update 
- [ ] Challenge Management / Challenge Provisioning / Challenge Submission
- [ ] Team Management/ Team Invitations
- [ ] User & Team Scoring System 
- [ ] Static files Issue/ Cache invalidation / HTTPS/TLS  

**Describe the bug**
Just after registration, the User avatar is not displayed
**To Reproduce**
1. Register a new user
2. Login 
3. Check the user profile

**Expected behavior**
User registration requires setting a default avatar 

**Screenshots**
<img width="307" alt="Screenshot 2021-04-10 at 22 35 34" src="https://user-images.githubusercontent.com/6031769/114283990-2b077380-9a4d-11eb-8e09-d735749c1db6.png">

**Desktop (please complete the following information):**
 - OS: Macos BigSur
 - Browser Firefox
 - Version -

**Additional context**

**Comment by Lina-Hammami** [comment]
I'm on it

**Comment by NabilHouidi** [comment]
U just need to pick a default icon from `assets/img/avatars` directory and
assign it as default when a user registers. Maybe we can add a grayed out
icon to that folder so the default icon is different (and not gendered)

**Comment by Lina-Hammami** [comment]
#https://github.com/eyacom/ctf-back/pull/56

**Comment by Lina-Hammami** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix ctf-platform-bugs](https://trello.com/c/MLcF2C2C/252-fix-ctf-platform-bugs)
