### ISSUE TITLE
User cannot login after updating his profile

### ISSUE THREAD

**Issue by yurilaaziz** [eyacom/ctf-platform-bugs#2]
**Describe the bug**

- [x] Login / Register / Authentication / Authorization
- [ ] User's profile display / User profile update 
- [ ] Challenge Management / Challenge Provisioning / Challenge Submission
- [ ] Team Management/ Team Invitations
- [ ] User & Team Scoring System 
- [ ] Static files Issue/ Cache invalidation / HTTPS/TLS  

**Describe the bug**
User can not login after updating his profile, 

**To Reproduce**
1. Login
2. Go to User profile ( click on avatar + Edit)
3. Make a change ( change the profile avatar or banner )
4. Logout
5. Try to login, see error 

**Expected behavior**
Update User profile should disable user login 

**Screenshots**

**Desktop (please complete the following information):**

 * OS:  
   - [ ] Windows
   - [x] MacOs
   - [ ] GNU/Linux
   - [ ] Other : ?
 * Browser 
   - [x] Firefox
   - [ ] Chrome
   - [ ] Safari
   - [ ] Other : ?
 * Version : ?

**Additional context**

**Comment by Lina-Hammami** [comment]
I'm on it

**Comment by Lina-Hammami** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix ctf-platform-bugs](https://trello.com/c/MLcF2C2C/252-fix-ctf-platform-bugs)
