### ISSUE TITLE
User cannot change his password

### ISSUE THREAD

**Issue by yurilaaziz** [eyacom/ctf-platform-bugs#3]
**Describe the bug**

- [x] Login / Register / Authentication / Authorization
- [ ] User's profile display / User profile update 
- [ ] Challenge Management / Challenge Provisioning / Challenge Submission
- [ ] Team Management/ Team Invitations
- [ ] User & Team Scoring System 
- [ ] Static files Issue/ Cache invalidation / HTTPS/TLS  

**Describe the bug**

The user cannot change his password. Default Admin password must be changed 

**To Reproduce**
1. Login
2. Go to User Profile
3. Nothing to change the user's password

**Expected behavior**
A User must have ability to change his password

**Screenshots**

**Desktop (please complete the following information):**

 * OS:  
   - [ ] Windows
   - [x] MacOs
   - [ ] GNU/Linux
   - [ ] Other : ?
 * Browser 
   - [x] Firefox
   - [ ] Chrome
   - [ ] Safari
   - [ ] Other : ?
 * Version : ?

**Additional context**

**Comment by Lina-Hammami** [comment]
I'm on it

**Comment by Lina-Hammami** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix ctf-platform-bugs](https://trello.com/c/MLcF2C2C/252-fix-ctf-platform-bugs)

**Comment by NabilHouidi** [comment]
fixed by https://github.com/eyacom/ctf-front/pull/104
