### ISSUE TITLE
Admin account is not reserved/created

### ISSUE THREAD

**Issue by yurilaaziz** [eyacom/ctf-platform-bugs#4]
**Describe the bug**

- [x] Login / Register / Authentication / Authorization
- [ ] User's profile display / User profile update 
- [ ] Challenge Management / Challenge Provisioning / Challenge Submission
- [ ] Team Management/ Team Invitations
- [ ] User & Team Scoring System 
- [ ] Static files Issue/ Cache invalidation / HTTPS/TLS  

**Describe the bug**
The admin account is not created, this must be reserved by launching a new instance of ctf-platform. 

**To Reproduce**
1. Deploy a new instance of ctf-platform
2. Register a new account with username admin

**Expected behavior**
admin username must be reserved. admin account must be created during ctf-platform's initial configuration 

**Screenshots**

**Desktop (please complete the following information):**

 * OS:  
   - [ ] Windows
   - [x] MacOs
   - [ ] GNU/Linux
   - [ ] Other : ?
 * Browser 
   - [x] Firefox
   - [ ] Chrome
   - [ ] Safari
   - [ ] Other : ?
 * Version : ?

**Additional context**

**Comment by Lina-Hammami** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix ctf-platform-bugs](https://trello.com/c/MLcF2C2C/252-fix-ctf-platform-bugs)

**Comment by NabilHouidi** [comment]
Can be resolved by https://github.com/eyacom/ctf-back/pull/59
