### ISSUE TITLE
Progress bar is not updating correctly

### ISSUE THREAD

**Issue by OlfaBensoussia** [eyacom/ctf-platform-bugs#5]
**Describe the bug**

- [ ] Login / Register / Authentication / Authorization
- [ ] User's profile display / User profile update 
- [ ] Challenge Management / Challenge Provisioning / Challenge Submission
- [ ] Team Management/ Team Invitations
- [x] User & Team Scoring System 
- [ ] Static files Issue/ Cache invalidation / HTTPS/TLS  

**Describe the bug**
The progress bar is updated whether the flag submitted is true or false.

**To Reproduce**
1. Go to any challenge
2. Enter an incorrect flag
3. Watch the progress bar getting updated 

**Expected behavior**
progress bar should be updated when a user submits a correct flag

**Screenshots**

**Desktop (please complete the following information):**

 * OS:  
   - [x] Windows
   - [ ] MacOs
   - [ ] GNU/Linux
   - [ ] Other : ?
 * Browser 
   - [ ] Firefox
   - [x] Chrome
   - [ ] Safari
   - [ ] Other : ?
 * Version : ?

**Additional context**

**Comment by Lina-Hammami** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix ctf-platform-bugs](https://trello.com/c/MLcF2C2C/252-fix-ctf-platform-bugs)

**Comment by OlfaBensoussia** [comment]
fixed in a previous PR

**Comment by NabilHouidi** [comment]
Can you add the  link of the relevant PR please?

**Comment by OlfaBensoussia** [comment]
@NabilHouidi https://github.com/eyacom/ctf-front/pull/91
